import { Pool } from 'pg';

let pool: Pool;

// Initialize database pool with environment variables
export function initPool() {
  const dbConfig = {
    host: process.env.BACKEND_DB_HOST || 'localhost',
    port: parseInt(process.env.BACKEND_DB_PORT || '5432'),
    user: process.env.BACKEND_DB_USER || 'bobhack',
    password: process.env.BACKEND_DB_PASSWORD,
    database: process.env.BACKEND_DB_NAME || 'bobhack',
    max: 20,
    idleTimeoutMillis: 30000,
    connectionTimeoutMillis: 2000,
  };

  console.log('DB Config:', {
    ...dbConfig,
    password: dbConfig.password ? `***${dbConfig.password.slice(-4)}` : 'undefined',
    passwordType: typeof dbConfig.password
  });

  pool = new Pool(dbConfig);
  return pool;
}

// Initialize database and create tables
export async function initializeDatabase(): Promise<void> {
  try {
    console.log('Connecting to database...');
    
    // Test connection
    const client = await getPool().connect();
    console.log('Database connected successfully!');
    
    // Create users table if it doesn't exist
    await client.query(`
      CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        name VARCHAR(255) NOT NULL,
        google_id VARCHAR(255),
        picture TEXT,
        last_login TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);
    console.log('Users table created/verified!');

    await client.query(`
      CREATE TABLE IF NOT EXISTS settings (
        id SERIAL PRIMARY KEY,
        dify_api_key TEXT NOT NULL,
        dify_api_url TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    console.log('Settings table created/verified!');
    
    // Add OAuth columns if they don't exist (migration for existing tables)
    console.log('Running OAuth columns migration...');
    try {
      await client.query(`
        ALTER TABLE users 
        ADD COLUMN IF NOT EXISTS google_id VARCHAR(255),
        ADD COLUMN IF NOT EXISTS picture TEXT,
        ADD COLUMN IF NOT EXISTS last_login TIMESTAMP
      `);
      console.log('✅ OAuth columns migration completed!');
    } catch (migrationError) {
      console.log('⚠️  OAuth columns migration skipped (columns may already exist)');
    }
    
    console.log('Users table is ready!');
    
    client.release();
  } catch (error) {
    console.error('Database initialization error:', error);
    throw error;
  }
}

// Export pool getter for queries
export function getPool() {
  if (!pool) {
    throw new Error('Database pool not initialized. Call initPool() first.');
  }
  return pool;
}

// Initialize retail schema with tables and data
export async function initializeRetailSchema(): Promise<void> {
  const client = await getPool().connect();
  try {
    console.log('Initializing retail schema...');
    
    await client.query('SET client_encoding = \'UTF8\'');
    await client.query('SET standard_conforming_strings = on');
    
    await client.query('DROP SCHEMA IF EXISTS retail CASCADE');
    await client.query('CREATE SCHEMA retail');
    await client.query('SET search_path TO retail');
    
    await client.query('BEGIN');
    
    // Create tables
    await client.query(`
      CREATE TABLE categories (
        category_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        description TEXT
      )
    `);
    
    await client.query(`
      CREATE TABLE suppliers (
        supplier_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        contact_email TEXT NOT NULL,
        phone TEXT,
        lead_time_days SMALLINT NOT NULL DEFAULT 5 CHECK (lead_time_days BETWEEN 1 AND 60)
      )
    `);
    
    await client.query(`
      CREATE TABLE stores (
        store_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        city TEXT NOT NULL,
        state CHAR(2) NOT NULL,
        opened_date DATE NOT NULL
      )
    `);
    
    await client.query(`
      CREATE TABLE products (
        product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_id SMALLINT NOT NULL REFERENCES categories,
        default_supplier_id SMALLINT REFERENCES suppliers,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        sku TEXT NOT NULL UNIQUE,
        unit_cost NUMERIC(10, 2) NOT NULL CHECK (unit_cost >= 0),
        unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= unit_cost),
        active BOOLEAN NOT NULL DEFAULT true
      )
    `);
    
    await client.query(`
      CREATE TABLE product_descriptions (
        product_id INTEGER NOT NULL REFERENCES products ON DELETE CASCADE,
        description_type TEXT NOT NULL CHECK (
          description_type IN (
            'usage',
            'design',
            'performance',
            'battery',
            'display',
            'connectivity',
            'durability',
            'warranty',
            'cooling'
          )
        ),
        content TEXT NOT NULL,
        PRIMARY KEY (product_id, description_type)
      )
    `);
    
    await client.query(`
      CREATE TABLE inventory (
        store_id SMALLINT NOT NULL REFERENCES stores ON DELETE CASCADE,
        product_id INTEGER NOT NULL REFERENCES products ON DELETE CASCADE,
        quantity INTEGER NOT NULL CHECK (quantity >= 0),
        restock_level INTEGER NOT NULL CHECK (restock_level >= 0),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        PRIMARY KEY (store_id, product_id)
      )
    `);
    
    // Insert data
    await client.query(`
      INSERT INTO categories (category_id, name, description) VALUES
        (1, 'Smartphones', 'Flagship candybar, foldable, and rugged mobile phones'),
        (2, 'Laptops', 'Ultrabooks, creative workstations, and gaming notebooks')
    `);
    
    await client.query(`
      INSERT INTO suppliers (supplier_id, name, contact_email, phone, lead_time_days) VALUES
        (1, 'Apex Mobile Supply', 'ops@apexmobile.example', '415-555-0124', 4),
        (2, 'Lumen Device Partners', 'hello@lumendevices.example', '646-555-0177', 6),
        (3, 'Cobalt Components', 'logistics@cobaltcomponents.example', '206-555-0148', 5)
    `);
    
    await client.query(`
      INSERT INTO stores (store_id, name, city, state, opened_date) VALUES
        (1, 'Urban Tech Hub', 'Seattle', 'WA', '2019-05-18'),
        (2, 'Midtown Experience Lab', 'New York', 'NY', '2020-11-07'),
        (3, 'Desert Innovation Loft', 'Phoenix', 'AZ', '2021-08-23')
    `);
    
    await client.query(`
      INSERT INTO products (product_id, category_id, default_supplier_id, name, description, sku, unit_cost, unit_price, active) VALUES
        (1, 1, 1, 'Aurora X1 Pro 5G', 'Flagship 6.8 inch AMOLED phone with adaptive 120Hz LTPO display and triple spectral camera array', 'PHN-AUR-X1P', 560.00, 949.00, true),
        (2, 1, 2, 'Pioneer Fold 2 Dual Display', 'Second generation foldable with 7.9 inch interior OLED panel and hinge certified for 400k cycles', 'PHN-PIO-F2', 900.00, 1449.00, true),
        (3, 1, 3, 'Stratos Lite 5G', 'Featherweight 6.2 inch traveler phone with dual eSIM, Wi Fi 7, and ceramic shield frame', 'PHN-STR-LT5', 310.00, 599.00, true),
        (4, 1, 1, 'EchoMax Rugged 5G', 'MIL STD 810H rated 6.1 inch device with thermal camera, lidar, and glove friendly buttons', 'PHN-ECH-R5G', 380.00, 749.00, true),
        (5, 1, 2, 'Celestia Note Ultra', 'Stylus first 6.9 inch phablet with satellite messaging and 1TB UFS 4.0 storage option', 'PHN-CEL-ULT', 620.00, 1049.00, true),
        (6, 2, 2, 'VelaBook 14 Evo', '14 inch magnesium ultrabook with OLED HDR touchscreen, 32GB LPDDR5X, and 1TB PCIe Gen4 SSD', 'LTP-VEL-14E', 740.00, 1249.00, true),
        (7, 2, 3, 'Helios 16 Gaming Laptop', '16 inch QHD 240Hz gaming notebook with Ryzen 9 silicon and RTX 4080 Laptop GPU plus vapor chamber cooling', 'LTP-HEL-16G', 1150.00, 1899.00, true),
        (8, 2, 1, 'Quanta Studio 15 OLED', 'Creator focused 15 inch mobile workstation with dual USB4, SD Express, and calibrated 4K OLED panel', 'LTP-QNT-15O', 980.00, 1649.00, true),
        (9, 2, 1, 'Momentum Air 13', 'Fanless 13 inch ultralight with 28W performance core, recycled chassis, and 20 hour battery', 'LTP-MOM-A13', 620.00, 1099.00, true),
        (10, 2, 2, 'Nebula Creator 17', '17 inch mini LED workstation with dual SSD bays, studio grade audio, and 12 port expansion bar', 'LTP-NEB-17C', 1180.00, 1999.00, true)
    `);
    
    await client.query(`
      INSERT INTO product_descriptions (product_id, description_type, content) VALUES
        (1, 'usage', 'Capture 8K cinematic video, edit RAW stills, and cast to Wi Fi 7 displays without dropped frames'),
        (1, 'performance', 'Powered by the Nebula X3 4nm platform with 16GB LPDDR5X so gaming, editing, and streaming stay fluid'),
        (1, 'battery', '5,100 mAh graphene enhanced cell reaches 80 percent in 23 minutes using the bundled 80W charger'),
        (2, 'usage', 'Unfold the 7.9 inch canvas for dual app dashboards, whiteboarding, or timeline scrubbing on-site'),
        (2, 'design', 'Armor fiber exterior and sapphire coated hinge cover keep fingerprints down while staying pocketable'),
        (2, 'durability', 'Lab certified for 400k folds with IPX2 splash protection so daily opening never feels fragile'),
        (3, 'usage', 'Swap between work and travel profiles with dual eSIM slots and offline navigation baked in'),
        (3, 'performance', 'Equipped with the Atlas 7 Gen 2 chip and vapor cooling pad to sustain peak clocks in hot climates'),
        (3, 'battery', '4,300 mAh pack plus adaptive refresh nets up to 36 hours of moderate travel use per charge'),
        (4, 'usage', 'Thermal camera overlays, lidar scans, and push to talk controls let field teams document jobs quickly'),
        (4, 'durability', 'Reinforced aluminum bumper, Gorilla Glass Victus, and MIL STD 810H sealing shrug off drops and dust'),
        (4, 'battery', '6,000 mAh battery supports swappable hot charge pucks for nonstop work shifts'),
        (5, 'usage', 'Annotate CAD files, sign docs, and sketch concepts with the zero latency Celestia Pen 3'),
        (5, 'display', '1,600 nit LTPO panel renders DCI P3 color accurately for photo proofing in bright studios'),
        (5, 'performance', 'Quantum Fusion chip with NPU acceleration speeds handwriting search and multi window workflows'),
        (6, 'performance', '13th gen Core Ultra processor and 32GB LPDDR5X keep 8K timelines and code builds humming'),
        (6, 'display', '2.8K OLED HDR touchscreen covers 100 percent P3 with touch and pen support for content reviews'),
        (6, 'design', '1.1kg magnesium frame, edge to edge glass trackpad, and stealth hinge vents suit travel setups'),
        (7, 'performance', 'Ryzen 9 7945HX paired with RTX 4080 Laptop GPU sustains 150W for marathon renders or esports play'),
        (7, 'display', '16 inch QHD+ 240Hz panel with mini LED backlight and NVIDIA G Sync ensures crisp motion'),
        (7, 'cooling', 'Dual vapor chambers, liquid metal TIM, and four exhaust zones drop temps 12C under peak load'),
        (8, 'usage', 'Grade footage, run multi monitor color sessions, or render assets while tethered to fast storage'),
        (8, 'display', 'Factory calibrated 4K OLED covers 100 percent Adobe RGB with Delta E < 1 out of the box'),
        (8, 'connectivity', 'Dual USB4, SD Express 8.0, HDMI 2.1, and 2.5G Ethernet keep peripherals and fast networks attached'),
        (9, 'usage', 'Draft decks, browse, and hop on calls in silence thanks to the fanless 28W platform'),
        (9, 'design', 'Recycled aluminum shell weighs 0.95kg and uses a full size backlit keyboard despite the 13 inch frame'),
        (9, 'battery', '77Wh pack plus adaptive charging stretches to 20 hours of mixed productivity'),
        (10, 'usage', 'Drive dual 6K displays, external GPUs, and high speed arrays from the 12 port expansion bar'),
        (10, 'performance', '13th gen HX silicon, RTX 4090 Laptop GPU option, and 64GB DDR5 handle AI and 3D scene builds'),
        (10, 'display', '17 inch mini LED panel hits 1,200 nits peak with local dimming for precise HDR compositing')
    `);
    
    await client.query(`
      INSERT INTO inventory (store_id, product_id, quantity, restock_level, updated_at) VALUES
        (1, 1, 22, 8, '2024-05-02 09:10:00-07'),
        (1, 2, 10, 4, '2024-05-02 09:12:00-07'),
        (1, 3, 28, 9, '2024-05-02 09:14:30-07'),
        (1, 4, 15, 5, '2024-05-02 09:16:00-07'),
        (1, 5, 18, 6, '2024-05-02 09:18:00-07'),
        (1, 6, 12, 4, '2024-05-02 09:20:00-07'),
        (1, 7, 6, 3, '2024-05-02 09:21:30-07'),
        (1, 9, 20, 6, '2024-05-02 09:23:00-07'),
        (2, 1, 30, 10, '2024-05-02 12:05:00-04'),
        (2, 3, 24, 8, '2024-05-02 12:06:20-04'),
        (2, 5, 20, 6, '2024-05-02 12:07:40-04'),
        (2, 6, 16, 6, '2024-05-02 12:09:00-04'),
        (2, 7, 11, 4, '2024-05-02 12:10:20-04'),
        (2, 8, 9, 3, '2024-05-02 12:11:40-04'),
        (2, 9, 18, 6, '2024-05-02 12:12:50-04'),
        (2, 10, 7, 3, '2024-05-02 12:13:40-04'),
        (3, 2, 14, 5, '2024-05-02 11:01:00-07'),
        (3, 3, 18, 6, '2024-05-02 11:02:20-07'),
        (3, 4, 12, 4, '2024-05-02 11:03:40-07'),
        (3, 5, 15, 5, '2024-05-02 11:05:00-07'),
        (3, 6, 8, 3, '2024-05-02 11:06:20-07'),
        (3, 8, 11, 4, '2024-05-02 11:07:40-07'),
        (3, 9, 17, 6, '2024-05-02 11:08:50-07'),
        (3, 10, 9, 3, '2024-05-02 11:10:10-07')
    `);
    
    await client.query('COMMIT');
    
    console.log('✅ Retail schema initialized successfully!');
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('❌ Retail schema initialization error:', error);
    throw error;
  } finally {
    client.release();
  }
}
